disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
enabled_rules:
 - unneeded_parentheses_in_closure_argument
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods

