disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - line_length
 - unused_optional_binding
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods

